package lsieun.util;

import org.junit.Test;

public class MD5UtilTest {
    @Test
    public void testMd5() {
        String s = "Hello MD5";
        System.out.println("Your HashCode Generated by MD5 is: " + MD5Util.md5(s));
        System.out.println("Your HashCode Generated by MD5 is: " + MD5Util.md5_2(s));
        System.out.println("Your HashCode Generated by MD5 is: " + MD5Util.md5_3(s));
    }
}
