package lsieun.md;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class MD5JDK {
    public static void main(String[] args) {
        String s = "Hello MD5";
        System.out.println("Your HashCode Generated by MD5 is: " + getMD5(s)); // e5dadf6524624f79c3127e247f04b548
        System.out.println(getMD5("a quick brown fox jumped over a lazy dog"));
        System.out.println(getMD5("a quick blue fox jumped over a lazy dog"));
        System.out.println(getMD5("a quick brown dog jumped over a lazy fox"));
    }

    public static String getMD5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(input.getBytes());
            byte[] messageDigest = md.digest();

            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < messageDigest.length; ++i) {
                sb.append(Integer.toHexString((messageDigest[i] & 0xFF) | 0x100).substring(1,3));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        return null;
    }

}
