package lsieun.md;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class SHA1JDK {
    public static void main(String[] args) {
        String s = "hello world";
        System.out.println("Your HashCode Generated by SHA-1 is: " + getSHA1(s)); // 2aae6c35c94fcfb415dbe95f408b9ce91ee846ed
    }

    public static String getSHA1(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            md.update(input.getBytes());
            byte[] messageDigest = md.digest();

            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < messageDigest.length; ++i) {
                sb.append(Integer.toHexString((messageDigest[i] & 0xFF) | 0x100).substring(1,3));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        return null;
    }
}
